### ISSUE TITLE
Upgrade to version 0.14

### ISSUE THREAD

**Issue by ikegami-yukino** [HeartSaVioR/fluent-plugin-redis-multi-type-counter#2]
Hello.
I'm interested in fluent-plugin-redis-multi-type-counter.

In Ruby gem, the version of this plugin is 0.14.
But the version of that in this repository is 0.13.
For this reason, I hope that this repository is upgraded.

Thank you.

**Comment by HeartSaVioR** [comment]
I can't find an information about 0.1.4, maybe 0.1.4 was released by accident.
So I've yanked 0.1.4 from rubygems. Thanks a lot!

**Comment by ikegami-yukino** [comment]
I see.
I understood the situation.

**Comment by ikegami-yukino** [comment]
Sorry, I forgot closing this issue.
